Repository Laskyyy/Create-Astral, pull requests merged in 2025-06, with the labels that each got.

#539 Shortman's 2.1.4 bug fixes
  .packwizignore
  index.toml
  kubejs/assets/createastral/lang/en_us.json
  kubejs/data/c/tags/blocks/storage_blocks/copper.json
  kubejs/data/c/tags/items/storage_blocks/copper.json
  kubejs/data/tconstruct/tinkering/materials/stats/brass.json
  kubejs/data/tconstruct/tinkering/materials/stats/bronze.json
  kubejs/data/tconstruct/tinkering/materials/stats/electrum.json
  kubejs/data/tconstruct/tinkering/materials/stats/lead.json
  kubejs/data/tconstruct/tinkering/materials/stats/silver.json
  kubejs/data/tconstruct/tinkering/materials/stats/steel.json
  kubejs/data/tconstruct/tinkering/materials/stats/tin.json
  kubejs/data/tconstruct/tinkering/materials/stats/tungsten.json
  kubejs/data/tconstruct/tinkering/materials/stats/zinc.json
  kubejs/data/tconstruct/tinkering/materials/traits/bone.json
  kubejs/data/tconstruct/tinkering/tool_definitions/cleaver.json
  kubejs/data/tconstruct/tinkering/tool_definitions/excavator.json
  kubejs/data/tconstruct/tinkering/tool_definitions/pickaxe.json
  kubejs/data/tconstruct/tinkering/tool_definitions/scythe.json
  kubejs/data/tconstruct/tinkering/tool_definitions/sledge_hammer.json
  kubejs/data/tconstruct/tinkering/tool_definitions/vein_hammer.json
  kubejs/server_scripts/recipes/create/cutting.js
  kubejs/server_scripts/recipes/minecraft/shaped.js
  kubejs/server_scripts/recipes/minecraft/stonecutting.js
  kubejs/server_scripts/recipes/removals.js
  kubejs/startup_scripts/tooltip/immersive_aircraft.js
  mods/copycats.pw.toml
  mods/quarry-reborn.pw.toml
  mods/roughly-enough-items.pw.toml
  pack.toml
Labels: WIP

#533 Bump Defined's Blocks to 1.0.2
  .gitignore
  .packwizignore
  flake.lock
  flake.nix
  index.toml
  mods/defineds-blocks.pw.toml
Labels: enhancement

#542 2.1.4/changelog
  CHANGELOG.md
Labels: documentation

#535 Miko's misc PR 2
  config/ftbquests/quests/chapters/chapter_4.snbt
  kubejs/assets/createastral/lang/en_us.json
  kubejs/assets/createastral/textures/gui/distillation_tower/distillation_tower_gui.png
  kubejs/assets/createastral/textures/gui/distillation_tower/distillation_tower_progress_empty.png
  kubejs/assets/createastral/textures/gui/distillation_tower/distillation_tower_progress_full.png
  kubejs/assets/createastral/textures/gui/electrolyzer/electrolyzer_gui.png
  kubejs/assets/createastral/textures/gui/electrolyzer/electrolyzer_progress_bar_empty.png
  kubejs/assets/createastral/textures/gui/electrolyzer/electrolyzer_progress_bar_full.png
  kubejs/assets/createastral/textures/gui/electrolyzer/electrolyzer_tank.png
  kubejs/assets/createastral/textures/gui/electrolyzer_gui.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_energy_empty.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_energy_full.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_gui.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_progress_empty.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_progress_full.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_slot.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_status_idle.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_status_running.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_tank.png
  kubejs/assets/createastral/textures/gui/refinery/refinery_tank_texture.png
  kubejs/assets/createastral/textures/gui/sgc/sgc_gui.png
  kubejs/assets/createastral/textures/gui/sgc/sgc_slot.png
  kubejs/assets/createastral/textures/gui/sgc_gui.png
  kubejs/assets/createastral/textures/item/incomplete_shimmer_amplifier.png
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/client_scripts/rei.js
  kubejs/data/create/tags/blocks/wrench_pickup.json
  kubejs/data/createastral/machines/distillery.json
  kubejs/data/createastral/machines/electrolyser.json
  kubejs/data/createastral/machines/shimmer_refinery.json
  kubejs/data/createastral/machines/stone_growth_chamber.json
  kubejs/server_scripts/recipes/create/sequenced_assembly.js
  kubejs/server_scripts/recipes/minecraft/shaped.js
  kubejs/server_scripts/recipes/removals.js
  kubejs/server_scripts/recipes/replacements.js
  kubejs/server_scripts/recipes/techreborn/centrifuge.js
  kubejs/startup_scripts/registry/createastral/item/item.js
Labels: type: enhancement, type: bugfix, status: awaiting approval
